//
//  CRVLinguist.m
//  codereview
//
//  Created by Jackson Harper on 12/18/13.
//  Copyright (c) 2013 Harper Semiconductors, Inc. All rights reserved.
//

#import "CRVLinguist.h"
#import "crvdiff.h"

@implementation CRVLinguist


+ (BOOL)isGeneratedFile:(CRVDiffFile *)file
{
	NSString *name = [file newFilePath];
	NSString *lowercaseName = [name lowercaseString];

	if ([name isEqualToString:@"Gemfile.lock"])
		return YES;

	NSString *ext = [lowercaseName pathExtension];
	if ([self isXcodeProjectFileExtension:ext])
		return YES;
	
	if ([self isDotNetDesignerFileWithLowercaseName:lowercaseName])
		return YES;
	
	if ([self isNodeModulesFileNamed:lowercaseName])
		return YES;

	return NO;
}

+ (BOOL)isXcodeProjectFileExtension:(NSString *)ext
{
	return ([ext isEqualToString:@"xib"] ||
			[ext isEqualToString:@"nib"] ||
			[ext isEqualToString:@"storyboard"] ||
			[ext isEqualToString:@"pbxproj"] ||
			[ext isEqualToString:@"xcworkspacedata"] ||
			[ext isEqualToString:@"xcuserstate"]);
}

+ (BOOL)isDotNetDesignerFileWithLowercaseName:(NSString *)name
{
	return [name hasSuffix:@".designer.cs"];
}

+ (BOOL)isProtoBufFileNamed:(NSString *)file withBody:(NSString *)body
{
	if (![file isEqualToString:@"py"] && ![file isEqualToString:@"java"] &&
		![file isEqualToString:@"h"] && ![file isEqualToString:@"cc"] &&
		![file isEqualToString:@"cpp"])
		return NO;
	
	return [body hasPrefix:@"Generated by the protocol buffer compiler.  DO NOT EDIT!"];
}

+ (BOOL)isNodeModulesFileNamed:(NSString *)file
{
	return ([file rangeOfString:@"node_modules"].length > 0);
}

@end
